# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_imagen',
            fields=[
                ('arim_id', models.AutoField(primary_key=True, serialize=False)),
                ('arim_pos_x', models.DecimalField(decimal_places=3, max_digits=19)),
                ('arim_pos_y', models.DecimalField(decimal_places=3, max_digits=19)),
                ('arim_ancho', models.DecimalField(decimal_places=3, max_digits=19)),
                ('arim_alto', models.DecimalField(decimal_places=3, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_area_img',
            fields=[
                ('det_a_im_id', models.AutoField(primary_key=True, serialize=False)),
                ('arim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanm.Area_imagen', verbose_name='area de imegen')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_ruta', models.CharField(max_length=300)),
                ('img_descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='detalle_area_img',
            name='img_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanm.Imagen', verbose_name='imagen'),
        ),
    ]
