# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import scanm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[scanm.models.validar_cedula])),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('m', 'Malculino'), ('f', 'Femenino')], max_length=2)),
                ('fecha_de_nacimiento', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Area_imagen',
            fields=[
                ('arim_id', models.AutoField(primary_key=True, serialize=False)),
                ('arim_pos_x', models.DecimalField(decimal_places=3, max_digits=19)),
                ('arim_pos_y', models.DecimalField(decimal_places=3, max_digits=19)),
                ('arim_ancho', models.DecimalField(decimal_places=3, max_digits=19)),
                ('arim_alto', models.DecimalField(decimal_places=3, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_clinico',
            fields=[
                ('hc_id', models.AutoField(primary_key=True, serialize=False)),
                ('hc_nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('hc_apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('hc_edad', models.IntegerField(verbose_name='Edad')),
                ('hc_fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hc_estado', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=25, verbose_name='Estado')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_ruta', models.ImageField(upload_to='user_media')),
                ('img_descripcion', models.TextField(blank=True, default='sin comentarios...', verbose_name='Descripcion de la imagen')),
                ('img_estado', models.CharField(blank=True, choices=[('analizada', 'Analizada'), ('no analizada', 'No Analizada')], default='no analizada', max_length=25)),
                ('img_validez', models.CharField(blank=True, choices=[('valida', 'Valida'), ('no definido', 'No definido'), ('no valida', 'No Valida')], default='no definido', max_length=25)),
                ('img_fecha', models.DateField(auto_now_add=True)),
                ('hc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanm.Historial_clinico', verbose_name='Historial clinico')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_adm',
            fields=[
                ('imgad_id', models.AutoField(primary_key=True, serialize=False)),
                ('imgad_ruta', models.ImageField(upload_to='admin_media')),
                ('imgad_descripcion', models.TextField(blank=True, default='sin comentarios...', verbose_name='Descripcion de la imagen')),
                ('imgad_fecha', models.DateField(auto_now_add=True)),
                ('imgad_ancho', models.CharField(max_length=100)),
                ('imgad_alto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados_analisis',
            fields=[
                ('resan_id', models.AutoField(primary_key=True, serialize=False)),
                ('resan_fecha', models.DateField(auto_now_add=True)),
                ('resan_descripcion', models.TextField()),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanm.Imagen', verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_cancer',
            fields=[
                ('tc_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc_nombre', models.CharField(max_length=25)),
                ('tc_descripcion', models.TextField()),
                ('tc_estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='resultados_analisis',
            name='tc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanm.Tipo_cancer', verbose_name='tipo_cancer'),
        ),
        migrations.AddField(
            model_name='imagen_adm',
            name='tc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanm.Tipo_cancer', verbose_name='Tipo de cancer'),
        ),
        migrations.AddField(
            model_name='area_imagen',
            name='imgad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanm.Imagen_adm', verbose_name='imagen'),
        ),
    ]
